management:
  endpoints:
    web:
      exposure:
        include: health

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  jackson:
    default-property-inclusion: non_absent  # For debugging, you can change it to get all the fields in API responses

# debug spring security
#    org.springframework.security: TRACE

#  h2:
#    console.enabled: true  # You can get a browser based db management tool

