management:
  endpoints:
    web:
      exposure:
        include: health

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
# only for debugging purposes
#  h2:
#    console.enabled: true
