### Health Check

GET {{base-url}}/actuator/health

### Not found
GET {{base-url}}/idontexists

### User management - Sign up

POST {{base-url}}/users
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "!littleStuff123_!"
}

### User management - Sign up - Invalid password

POST {{base-url}}/users
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "123"
}
